### ISSUE TITLE
Gitleaks v8

### ISSUE THREAD

**Issue by JoostVoskuil** [jessehouwing/gitleaks-azure#2]
Hi @jessehouwing ,

Gitleaks 8 is out, a massive change in how Gitleaks works. The configuration definition are also changed. I am wondering if you have time to look at the changes to make a new version of the UDM config that is compatible with v8? I spent a couple of minutes but I can't figure out why it does not detect any secrets. Still a n00b in regex ;). If you don't have time no problem, I will spent more time then.

I am almost finished with the Azure DevOps wrapper for v8 (version 2 of the task)

**Comment by jessehouwing** [comment]
Somobohy already did that and  I merged it.

**Comment by JoostVoskuil** [comment]
That was for v7 I think. The structure again changed for v8

**Comment by JoostVoskuil** [comment]
See #3 for a new v8 file
