### ISSUE TITLE
Passwords in the code are not detecting using the predefined config file

### ISSUE THREAD

**Issue by priyankavit** [jessehouwing/gitleaks-azure#6]
I'm using the predefined config file (GitleaksUdmCombo.toml) for gitleaks scan, but it is not able to recognize the password information (password key) though it is there in the code.

Could you please share the predefined configuration file for gitleaks scan
and help me how can we identify the password information.
Thanks in advance..!!!!

**Comment by JoostVoskuil** [comment]
Are you using the Azure DevOps extension of gitleaks?

Either way. I don't think we can help you since we cannot know the password you are referring to. We need at least an example

**Comment by priyankavit** [comment]
yes I am using Azure devops extension of gitleaks from marketplace

[test.txt](https://github.com/jessehouwing/gitleaks-azure/files/11155830/test.txt)

In this yaml file there is DB secret information like password but it is not able to detect the password though it is sensitive information
I am using the same gitleaks.toml file to recognize the password..it is showing the password in finding but the line number it is referring to and other information is wrong.. we need the abstract information
Example of console output:
Finding: ..tps://xxx.com
Secret: REDACTED
RuleID: password
Line:109
Commit: XXXXXX
Fingerprint: test.yml:password:109

We dont see the password in line 109 but the actual line number of password information is in different line.

**Comment by JoostVoskuil** [comment]
Hi @priyankavit It is hard for me to understand your problem.
Can you re-run the scan with the Azure DevOps extension? I've updated the extension with the latest configuration files.

**Comment by JoostVoskuil** [comment]
@priyankavit any news?

**Comment by JoostVoskuil** [comment]
@jessehouwing can you close this? Thanx
